### ISSUE TITLE
gentoo ebuild

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [daviderestivo/fortune-mod-woody-allen-it#1]
I've restored the ebuild here https://github.com/Alessandro-Barbieri/fortunelay/tree/master/games-misc/fortune-mod-woody-allen-it

**Comment by daviderestivo** [comment]
Hi @Alessandro-Barbieri,

thanks a lot :). I guess I can close this issue since I assume this was more informational than an issue :).
